/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Card = IDL.Record({
  'bio' : IDL.Text,
  'linkedin' : IDL.Text,
  'twitter' : IDL.Text,
  'name' : IDL.Text,
  'email' : IDL.Text,
  'website' : IDL.Text,
  'company' : IDL.Text,
  'jobTitle' : IDL.Text,
  'phone' : IDL.Text,
  'location' : IDL.Text,
});

export const idlService = IDL.Service({
  'getCard' : IDL.Func([], [Card], ['query']),
  'updateCard' : IDL.Func([Card], [], []),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Card = IDL.Record({
    'bio' : IDL.Text,
    'linkedin' : IDL.Text,
    'twitter' : IDL.Text,
    'name' : IDL.Text,
    'email' : IDL.Text,
    'website' : IDL.Text,
    'company' : IDL.Text,
    'jobTitle' : IDL.Text,
    'phone' : IDL.Text,
    'location' : IDL.Text,
  });
  
  return IDL.Service({
    'getCard' : IDL.Func([], [Card], ['query']),
    'updateCard' : IDL.Func([Card], [], []),
  });
};

export const init = ({ IDL }) => { return []; };